# Generated by Django 3.2 on 2025-03-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drop', 'Drop'), ('inhaler', 'Inhaler'), ('other', 'Other')], max_length=50)),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pack_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('box_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_stock', models.PositiveIntegerField(default=0)),
                ('strip_stock', models.PositiveIntegerField(default=0)),
                ('pack_stock', models.PositiveIntegerField(default=0)),
                ('box_stock', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_medicines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
